name: Playwright API Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: playwright install
      - name: Run API tests
        run: pytest -v --html-report=api_report.html tests/api
        env:
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
      - name: Upload pytest-html report
        uses: actions/upload-artifact@v3
        with:
          name: pytest-html-report
          path: /home/runner/work/buddy-program/buddy-program/api_report.html
