name: Playwright UI Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: pip install playwright
      - run: browserstack-sdk setup --framework "pytest" --username ${{ secrets.BROWSERSTACK_USERNAME }} --key ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      - run: playwright install
      - name: Run UI tests
        run: pytest -v --junitxml=report.xml tests/ui
        env:
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
      - name: Upload pytest-html report
        uses: actions/upload-artifact@v3
        with:
          name: pytest-html-report
          path: report.html