name: Playwright UI Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: pip install playwright
      - run: playwright install
      - name: Run UI tests
        run: pytest --alluredir=allure-results tests/ui
        env:
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Download Allure CLI
        run: |
          curl -o allure.zip -L https://github.com/allure-framework/allure2/releases/download/2.22.2/allure-2.22.2.zip
          unzip allure.zip -d allure
      - name: Generate Allure Report
        run: ./allure/bin/allure generate allure-results -o allure-report
      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report/
